version: '3.9'
services:
  dplus-update:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /volume1/docker/dplus-hs-sync:/app/data
    environment:
      - AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
      - AIRTABLE_WORKING_BASE=${AIRTABLE_WORKING_BASE}
    network_mode: 'host'
    restart: always
