version: '3.9' # optional since v1.27.0
services:
  dplus-update:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /volume1/docker/dplus-hs-sync:/app/data
    restart: always
